language: cpp
compiler: gcc
dist: bionic
notifications:
  email:
    recipients:
    - mchehab@kernel.org
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.ccache
  - $HOME/pbuilder-bases
matrix:
  include:
  - env: TARGET_OS=bionic
  - compiler: clang
    env: TARGET_OS=bionic
  #powerjobs
  - env: TARGET_OS=bionic
    arch: ppc64le
  - compiler: clang
    arch: ppc64le
    env: TARGET_OS=bionic
before_install:
- sudo apt-get install -y sqlite3
install:
- autoreconf -vfi
- ./configure --enable-sqlite3 --enable-aer --enable-non-standard --enable-arm --enable-mce --enable-extlog --enable-devlink --enable-diskerror --enable-abrt-report --enable-hisi-ns-decode --enable-memory-ce-pfa

script:
- make && sudo make install
after_script:
- ccache -s
