# SPDX-License-Identifier: GPL-2.0

import os
import sys
import types
import unittest
from unittest import mock


ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT_DIR, "util"))

# ras_config.py is generated by Meson. Supply the interface needed when the
# tests run directly from an unconfigured source tree.
if "ras_config" not in sys.modules:
    ras_config = types.ModuleType("ras_config")

    class Sqlite3ConnParms:
        def __init__(self):
            self.database = os.environ.get(
                "RAS_SQLITE3_DATABASE",
                "/var/lib/rasdaemon/ras-mc_event.db",
            )

    ras_config.Sqlite3ConnParms = Sqlite3ConnParms
    sys.modules["ras_config"] = ras_config

from ras_env import RasDaemonEnv, RasdaemonConfig  # noqa: E402


class RasdaemonConfigTest(unittest.TestCase):
    def test_contrib_database_configs(self):
        cases = {
            "sqlite3": ("database", "/tmp/rasdaemon-test/rasdaemon-test.db"),
            "mysql": ("database", "rasdaemon_test"),
            "postgresql": ("database", "rasdaemon_test"),
        }

        for backend, (attribute, expected) in cases.items():
            with self.subTest(backend=backend), mock.patch.dict(
                os.environ, {}, clear=True
            ):
                path = os.path.join(
                    ROOT_DIR, "contrib", f"rasdaemon-{backend}.env"
                )
                self.assertEqual(RasDaemonEnv.ras_set_env(path), 0)
                config = RasdaemonConfig()
                self.assertEqual(config.db_backend, backend)
                params = (
                    config.pg_conn_parms
                    if backend == "postgresql"
                    else getattr(config, f"{backend}_conn_parms")
                )
                self.assertEqual(getattr(params, attribute), expected)


if __name__ == "__main__":
    unittest.main()
