name: Auto-remove "waiting new revision" label on PR update

on:
  pull_request:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove label on PR update
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'waiting new revision'
