name: Remove Waiting Label after update

on:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove label on PR update
        if: contains(github.event.pull_request.labels.*.name, 'waiting new revision')
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api --method DELETE \
            "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/waiting%20new%20revision"
