# SPDX-License-Identifier: GPL-2.0-only

name: Github RAS Daemon pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Sphinx
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson ninja-build python3 \
                                  libtraceevent-dev libpci-dev

      - name: Install Sphinx and its HTML theme
        run: pip install sphinx furo

      - name: Build docs
        run: make

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
