# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2026 Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

name: Unit Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Unittest:
    name: Default Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysqladmin ping --host=127.0.0.1 --user=root --password=root

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-client

          sudo systemctl start postgresql

          for attempt in {1..30}; do
            if pg_isready --host=127.0.0.1 --port=5432; then
              exit 0
            fi
            sleep 1
          done

          sudo systemctl status postgresql --no-pager

      - name: Setup PostgreSQL trust
        run: |
          HBA_FILE="$(sudo -u postgres psql --tuples-only --no-align \
              --command='SHOW hba_file')"
          sudo sed -i '1i local all rasdaemon trust' "$HBA_FILE"

          echo "Postgres config file $HBA_FILE:"
          sudo cat "$HBA_FILE"
          sudo systemctl restart postgresql

          for attempt in {1..30}; do
            if pg_isready --host=127.0.0.1 --port=5432; then
              exit 0
            fi
            sleep 1
          done

          sudo systemctl status postgresql --no-pager
          exit 1

      - name: Create MySQL database
        env:
          MYSQL_PWD: root
        run: |
          mysql --host=127.0.0.1 --user=root << EOF
            CREATE USER 'rasdaemon'@'%' IDENTIFIED BY 'mypass';
            CREATE DATABASE  rasdaemon_test;
            GRANT ALL PRIVILEGES ON rasdaemon_test.* TO 'rasdaemon'@'%';
            FLUSH PRIVILEGES;
          EOF
      - name: Create PostgreSQL database
        run: |
          sudo -u postgres psql --set ON_ERROR_STOP=1 << EOF
            CREATE USER rasdaemon WITH PASSWORD 'mypass';
            CREATE DATABASE rasdaemon_test OWNER rasdaemon;
          EOF

          PGPASSWORD='mypass' \
            psql -h /var/run/postgresql -U rasdaemon \
                 -d rasdaemon_test --set ON_ERROR_STOP=1 << EOF2
            CREATE SCHEMA rasdaemon AUTHORIZATION rasdaemon;
          EOF2
      - name: Install packages needed by Rasdaemon
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson ninja-build pkg-config \
                                  git cmake libsqlite3-dev sqlite3 \
                                  python3-sqlalchemy python3-mysqldb \
                                  python3-psycopg2 \
                                  libcmocka-dev libmysqlclient-dev libpq-dev \
                                  libtraceevent-dev libtraceevent1 libpci-dev
      - uses: actions/checkout@v7
      - name: Build rasdaemon
        run: |
          meson setup build
          make
      - name: Run C unit tests
        env:
          RAS_MYSQL_HOST: ''
          RAS_MYSQL_PORT: '3306'
          RAS_MYSQL_USER: rasdaemon
          RAS_MYSQL_PASSWORD: mypass
          RAS_MYSQL_DATABASE: rasdaemon_test
          RAS_MYSQL_SOCKET: ''
          RAS_MYSQL_USE_SSL: 'false'
          RAS_MYSQL_CONNECT_TIMEOUT: '10'
          RAS_PG_HOST: ''
          RAS_PG_PORT: 5432
          RAS_PG_USER: rasdaemon
          RAS_PG_PASSWORD: mypass
          RAS_PG_SCHEMA: rasdaemon
          RAS_PG_DATABASE: rasdaemon_test
        run: |
          build/unittest -o tap
      - name: Run Python unit tests
        env:
          RAS_MYSQL_HOST: ''
          RAS_MYSQL_PORT: '3306'
          RAS_MYSQL_USER: rasdaemon
          RAS_MYSQL_PASSWORD: mypass
          RAS_MYSQL_DATABASE: rasdaemon_test
          RAS_MYSQL_SOCKET: ''
          RAS_MYSQL_USE_SSL: 'false'
          RAS_MYSQL_CONNECT_TIMEOUT: '10'
          RAS_PG_HOST: ''
          RAS_PG_PORT: 5432
          RAS_PG_USER: rasdaemon
          RAS_PG_PASSWORD: mypass
          RAS_PG_SCHEMA: rasdaemon
          RAS_PG_DATABASE: rasdaemon_test
        run: |
          python3 tests/run.py -vvv

  MariaDBUnittest:
    name: MariaDB Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Start MariaDB
        run: |
          sudo apt-get remove -y mysql-server mysql-client
          sudo apt-get install -y mariadb-server mariadb-client
          sudo systemctl start mariadb.service

          sudo mysqladmin ping

      - name: Create MariaDB database
        env:
          MYSQL_PWD: root
        run: |
          sudo mysql << EOF
            CREATE USER 'rasdaemon'@'%' IDENTIFIED BY 'mypass';
            CREATE DATABASE  rasdaemon_test;
            GRANT ALL PRIVILEGES ON rasdaemon_test.* TO 'rasdaemon'@'%';
            FLUSH PRIVILEGES;
          EOF
      - name: Install packages needed by Rasdaemon
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson ninja-build pkg-config \
                                  git cmake libsqlite3-dev sqlite3 \
                                  python3-sqlalchemy python3-mysqldb \
                                  libcmocka-dev libmariadb-dev-compat \
                                  libtraceevent-dev libtraceevent1 libpci-dev
      - uses: actions/checkout@v7
      - name: Build rasdaemon
        run: |
          meson setup build
          make
      - name: Run MariaDB unit tests
        env:
          RAS_MYSQL_HOST: ''
          RAS_MYSQL_PORT: '3306'
          RAS_MYSQL_USER: rasdaemon
          RAS_MYSQL_PASSWORD: mypass
          RAS_MYSQL_DATABASE: rasdaemon_test
          RAS_MYSQL_SOCKET: ''
          RAS_MYSQL_USE_SSL: 'false'
          RAS_MYSQL_CONNECT_TIMEOUT: '10'
        run: |-
          build/unittest -o tap -g mysql
      - name: Run Python unittests
        env:
          RAS_MYSQL_HOST: ''
          RAS_MYSQL_PORT: '3306'
          RAS_MYSQL_USER: rasdaemon
          RAS_MYSQL_PASSWORD: mypass
          RAS_MYSQL_DATABASE: rasdaemon_test
          RAS_MYSQL_SOCKET: ''
          RAS_MYSQL_USE_SSL: 'false'
          RAS_MYSQL_CONNECT_TIMEOUT: '10'
        run: |-
          python3 tests/run.py -vvv -k RasDatabaseTests MysqlRasDatabaseTest
